config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'register' => 'users#new'
  get 'users/edit'
  get 'users/show'
  get 'users/index'

  resources :companies do
    resources :departments
    resources :employees do
      delete 'terminate' => 'employees#destroy'
    end
  end

  get '/auth/:provider/callback', to: 'sessions#facebook'
  get '/success' => 'pages#success'


  resources :users
  resources :articles

  get 'new-company' => 'companies#new'
  get 'mycompanies' => 'companies#index'
  get 'companies/new'
  get 'companies/edit'
  get 'companies/show'
  get 'gen_companies' => 'companies#gen_companies'
  get '/done' => 'pages#done'

  get 'employees/new'
  get 'employees/edit'
  get 'employees/index'
  get 'employees/show'
  get 'departments/new'
  get 'departments/edit'
  get 'departments/show'
  get 'departments/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/write' => 'articles#new'
  get 'articles/edit'
  get 'articles/show'
  get 'articles/index'
  get '/search' => 'articles#search'
  get '/results' => 'articles#results'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :cover_photo
  belongs_to :user
  validates :title, :content, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update]

  def new
    @article = Article.new
  end

  def create
    # POST /articles
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.author = current_user.full_name
    if @article.save
      p "article saved!"
      redirect_to @article
    else
      p 'Article rejected for errors'
      p @article.errors.messages
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      p "article successfully updated"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def show
  end

  def index
    # GET /articles
    @articles = Article.all.order('CREATED_AT DESC')
  end

  def search

  end

 def results
   @results = params[:q]
   p params[:date_submitted]
   # if params[:terms].to_i != 1
   #   p 'User did not agree :/'
   #   render 'search'
   # end
   search_words = params[:q].downcase.split(' ')
   titles = Article.pluck(:title)
   matches = []
   @final_results = []
   search_words.each do |word|
     titles.each do |t|
       if t.downcase.include?(word)
         matches << t
       end
     end
   end
   matches.each do |match| #2
       x = Article.where(title: match) #2
       x.each do |y|
         @final_results << y
       end
   end
   @final_results
 end

  private

  def article_params
    params.require(:article).permit(:title, :author, :content, :cover_photo)
  end

  def find_article
    @article = Article.find(params[:id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def long_article?(a)
    if a.content.split('').count > 100
      msg = 'You may want to read this later'
    else
      msg = 'This is a quick read'
    end
    return msg
  end

end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>

<input type="text" name="article[title]" placeholder="Enter a title" id="article_title"><br>
<%= f.text_area :content, placeholder: 'What is this thicc post about' %><br>
<%= f.file_field :cover_photo %><br>
<%= f.submit 'Publish Article' %>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing <em><%= @article.title %></em></h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Recent Articles</h1>

<% @articles.each do |a| %>
<h3><%= link_to "#{a.title}", a %><br>
  <p><%= long_article?(a) %></p>
    <small>written <%= time_ago_in_words(a.created_at) %> ago</small></h3>
<% end %>

app/views/articles/new.html.erb
<h1>Write a New Post</h1>
<%= render 'form' %>

app/views/articles/results.html.erb
<h1>Articles matching "<%= params[:q] %>" </h1>

<p><%= @final_results.count %> results found</p>
<% @final_results.each do |res| %>
  <%= link_to "#{res.title}", res %><br>
<% end %>

app/views/articles/search.html.erb
<h1>Search Articles</h1>

<%= form_tag('/results', method: 'get') do %>

<%= text_field_tag(:q) %> <br>
<%= date_field_tag(:date_submitted) %><br>
<%= check_box_tag(:terms) %> I agree to the terms<br><br>
<%= submit_tag("Search") %>

<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

  <%# image_tag(@article.cover_photo, class: 'img-responsive') %><br>
<em>written by <%= @article.author %></em><br>
<%= link_to "Edit", edit_article_path %>
<p>
  <%= @article.content %>
</p>