config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'register' => 'users#new'
  get 'users/edit'
  get 'users/show'
  get 'users/index'

  resources :companies do
    resources :departments
    resources :employees do
      delete 'terminate' => 'employees#destroy'
    end
  end

  get '/auth/:provider/callback', to: 'sessions#facebook'
  get '/success' => 'pages#success'


  resources :users
  resources :articles

  get 'new-company' => 'companies#new'
  get 'mycompanies' => 'companies#index'
  get 'companies/new'
  get 'companies/edit'
  get 'companies/show'
  get 'gen_companies' => 'companies#gen_companies'
  get '/done' => 'pages#done'

  get 'employees/new'
  get 'employees/edit'
  get 'employees/index'
  get 'employees/show'
  get 'departments/new'
  get 'departments/edit'
  get 'departments/show'
  get 'departments/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/write' => 'articles#new'
  get 'articles/edit'
  get 'articles/show'
  get 'articles/index'
  get '/search' => 'articles#search'
  get '/results' => 'articles#results'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def new
    @company = Company.find(params[:company_id])
    @dept = Department.new
  end

  def create
    @company = Company.find(params[:company_id])
    @dept = Department.new(dept_params)
    @dept.company_id = @company.id
    if @dept.save
      msg = "New Department created! Let's get you some employees!"
      redirect_to company_department_path(@dept.company_id, @dept.id)
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @dept = Department.find(params[:id])
    @company = Company.find(@dept.company_id)
  end

  def index
  end

  private

  def dept_params
    params.require(:department).permit(:name)
  end

  def find_dept
    @dept = Department.find(params[:id])
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/edit.html.erb
<h1>Departments#edit</h1>
<p>Find me in app/views/departments/edit.html.erb</p>

app/views/departments/index.html.erb
<h1>Departments#index</h1>
<p>Find me in app/views/departments/index.html.erb</p>

app/views/departments/new.html.erb
<h1>New Department for <%= @company.name %></h1>

<%= form_for([@company, @dept]) do |f| %>

<%= f.label :name %><br>
<%= f.text_field :name %><br>

<p>
<%= f.submit 'Create Department' %>
</p>
<% end %>

app/views/departments/show.html.erb
<h4 style="color: #858585;"><%= @company.name %></h4>
<h1><%= @dept.name %> Department</h1>
<h3><span id="emp-count"><%= @dept.employees.count %></span> employees</h3>
<% @dept.employees.each do |e| %>
  <p><%= e.full_name %> - #<%= e.eid %> --- <%= link_to 'Terminate', company_employee_terminate_path(e.company_id, e.id), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'terminate' %></p>
<% end %>