config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'register' => 'users#new'
  get 'users/edit'
  get 'users/show'
  get 'users/index'

  resources :companies do
    resources :departments
    resources :employees do
      delete 'terminate' => 'employees#destroy'
    end
  end

  get '/auth/:provider/callback', to: 'sessions#facebook'
  get '/success' => 'pages#success'


  resources :users
  resources :articles

  get 'new-company' => 'companies#new'
  get 'mycompanies' => 'companies#index'
  get 'companies/new'
  get 'companies/edit'
  get 'companies/show'
  get 'gen_companies' => 'companies#gen_companies'
  get '/done' => 'pages#done'

  get 'employees/new'
  get 'employees/edit'
  get 'employees/index'
  get 'employees/show'
  get 'departments/new'
  get 'departments/edit'
  get 'departments/show'
  get 'departments/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/write' => 'articles#new'
  get 'articles/edit'
  get 'articles/show'
  get 'articles/index'
  get '/search' => 'articles#search'
  get '/results' => 'articles#results'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :departments
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  require 'curb'
  before_action :find_company, only: [:show, :edit]

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id
    if @company.save
      redirect_to @company
    else
      render 'new'
    end
  end

  def gen_companies
    count = 0
    1000.times {
      randomstring = SecureRandom.uuid
      x = Curl::Easy.perform("https://www.google.com/search?q=#{randomstring}")
      c = Company.new(name:"test company #{randomstring}", industry: "industry #{randomstring.split('')*1000}", user_id: 1)
      c.save
      count += 1
      p c.name
    }
    redirect_to '/done'
  end

  def edit
  end

  def show
    @company = Company.find(params[:id])
  end

  def index
    @companies = Company.where(user_id: current_user.id)
  end

  private

  def company_params
    params.require(:company).permit(:name, :industry)
  end

  def find_company
    @company = Company.find(params[:id])
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.erb
<h1>Companies#edit</h1>
<p>Find me in app/views/companies/edit.html.erb</p>

app/views/companies/index.html.erb
<h1> My Companies</h1>

<% @companies.each do |com| %>
  <%= link_to "#{com.name}", com %><br>
<% end %>

app/views/companies/new.html.erb
<h1>Register your Business</h1>
<p>Use our platform to put your business all out there!</p>

<%= form_for(@company) do |f| %>
  <label>Company Name</label><br>
  <%= f.text_field :name %><br>
  <label>What industry is your business in?</label><br>
  <%= f.text_field :industry %><br>
<p>
  <%= f.submit 'Register Company' %>
</p>
<% end %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>
<p><%= @company.industry %></p>

<h3>Your Departments</h3>

<% @company.departments.each do |dept| %>
  <h5><%= link_to "#{dept.name}", company_department_path(@company.id, dept.id)  %></h5>
<% end %>

<hr>

<%= link_to 'Create a Department', new_company_department_path(@company.id) %>
<%= link_to 'Add an Employee', new_company_employee_path(@company.id), data: {remote: true} %>


<div id="employee-form">
  <br><br><br>
<form class="" action="index.html" method="post">
  <input type="text" placeholder="Employee Name"><br>
  <input type="submit" value="Add employee">
</form>
</div>
<script> $('#employee-form').hide() </script>