config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'register' => 'users#new'
  get 'users/edit'
  get 'users/show'
  get 'users/index'

  resources :companies do
    resources :departments
    resources :employees do
      delete 'terminate' => 'employees#destroy'
    end
  end

  get '/auth/:provider/callback', to: 'sessions#facebook'
  get '/success' => 'pages#success'


  resources :users
  resources :articles

  get 'new-company' => 'companies#new'
  get 'mycompanies' => 'companies#index'
  get 'companies/new'
  get 'companies/edit'
  get 'companies/show'
  get 'gen_companies' => 'companies#gen_companies'
  get '/done' => 'pages#done'

  get 'employees/new'
  get 'employees/edit'
  get 'employees/index'
  get 'employees/show'
  get 'departments/new'
  get 'departments/edit'
  get 'departments/show'
  get 'departments/index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/write' => 'articles#new'
  get 'articles/edit'
  get 'articles/show'
  get 'articles/index'
  get '/search' => 'articles#search'
  get '/results' => 'articles#results'
  get 'pages/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<ul>
  <li><%= link_to 'Register', register_path %></li>
  <li><%= link_to 'All Articles', articles_path %></li>
  <li><%= link_to 'Write an Article', write_path %></li>
  <li><%= link_to 'Search', search_path %></li>
  <% if logged_in? %>
    <li><%= link_to "#{current_user.email}", '#' %></li>
    <li><%= link_to 'Log out', logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Log In', login_path %></li>
  <% end %>
</ul>

app/views/layouts/_header_ent.html.erb
<ul>
  <li><%= link_to "Home", root_path %></li>
  <% if logged_in? %>
    <li><%= link_to "#{current_user.email}", mycompanies_path %></li>
    <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    <li><%= link_to 'Create Company', new_company_path %></li>
  <% else %>
    <li><%= link_to 'Register', register_path %></li>
    <li><%= link_to 'Log In', login_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enterprise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1049944625187241',
      cookie     : true,
      xfbml      : true,
      version    : 'v3.1'
    });

    FB.AppEvents.logPageView();

  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
    <%= render 'layouts/header_ent' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>